# Generated by Django 2.2.7 on 2020-02-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pin', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30)),
                ('family_hist', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('DOB', models.DateTimeField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=400)),
                ('occupation', models.CharField(max_length=30)),
                ('marital_status', models.PositiveIntegerField()),
                ('acc_balance', models.PositiveIntegerField()),
                ('tel_num', models.PositiveIntegerField(null=True)),
                ('home_num', models.PositiveIntegerField(null=True)),
                ('next_app', models.DateTimeField(null=True)),
                ('recall_period', models.PositiveIntegerField(null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_symptoms', models.CharField(max_length=300, null=True)),
                ('doctor_notes', models.CharField(max_length=100, null=True)),
                ('outcome', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('further_actions', models.CharField(max_length=150)),
                ('ref_to', models.CharField(max_length=100, null=True)),
                ('ref_reason', models.CharField(max_length=150, null=True)),
                ('result', models.CharField(max_length=200)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('reg_pulse', models.BooleanField()),
                ('pulse_type', models.PositiveIntegerField()),
                ('protein', models.FloatField()),
                ('hdl_chol', models.FloatField(null=True)),
                ('ldl_chol', models.FloatField(null=True)),
                ('triglyceride', models.FloatField()),
                ('uric_acid', models.FloatField()),
                ('smoke_per_day', models.PositiveIntegerField()),
                ('smoker_years', models.PositiveIntegerField()),
                ('exerc_angina', models.BooleanField()),
                ('blood_systolic', models.FloatField()),
                ('blood_diastolic', models.FloatField()),
                ('chol_overall', models.FloatField()),
                ('fasting_glucose', models.FloatField()),
                ('pulse_rate', models.PositiveIntegerField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boards.Patient')),
                ('heart_attack', models.BooleanField()),
                ('angina', models.BooleanField()),
                ('breathlessness', models.BooleanField()),
                ('chest_pain', models.PositiveIntegerField()),
                ('high_chol', models.BooleanField()),
                ('high_bp', models.BooleanField()),
                ('hoarseness', models.BooleanField()),
                ('wheezing', models.BooleanField()),
                ('sweating', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('stressed', models.BooleanField()),
                ('childhood_illness', models.CharField(max_length=20, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Examination')),
            ],
        ),
    ]
