# Generated by Django 2.2.7 on 2020-03-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_examination_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='angina',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='breathlessness',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='chest_pain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='heart_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='high_bp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='high_chol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='hoarseness',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='stressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='sweating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='wheezing',
            field=models.BooleanField(default=False),
        ),
    ]
