# Generated by Django 2.2.7 on 2020-02-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200219_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AlterField(
            model_name='visit',
            name='outcome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
