# Generated by Django 2.2.7 on 2020-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200316_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='next_app',
        ),
        migrations.AlterField(
            model_name='patient',
            name='acc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_num',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel_num',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
