# Generated by Django 2.2.7 on 2020-02-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200219_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='patient_symptoms',
            new_name='reason',
        ),
    ]
