# Generated by Django 2.2.7 on 2020-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200326_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='app_length',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
