# Generated by Django 2.2.7 on 2020-02-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200219_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='exerc_angina',
        ),
    ]
