# Generated by Django 2.2.7 on 2020-03-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_visit_app_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
