# Generated by Django 2.2.7 on 2020-02-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20200221_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='result',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
