# Generated by Django 2.2.7 on 2020-03-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='smoke_per_day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='smoker_years',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='chest_pain',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recall_period',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='app_length',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
