# Generated by Django 2.2.7 on 2020-02-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20200229_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='date',
        ),
    ]
