# Generated by Django 2.2.7 on 2020-03-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20200327_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='chol_overall',
            new_name='chol_total',
        ),
    ]
