# Generated by Django 2.2.7 on 2020-03-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_remove_investigation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ailment_Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy_Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Ailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='ailment',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='ailment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='patient',
        ),
        migrations.AddField(
            model_name='ailment',
            name='name',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.CharField(default='def', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ailment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Reminders',
        ),
        migrations.AddField(
            model_name='patient_allergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Allergy'),
        ),
        migrations.AddField(
            model_name='patient_allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient'),
        ),
        migrations.AddField(
            model_name='patient_ailment',
            name='ailment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Ailment'),
        ),
        migrations.AddField(
            model_name='patient_ailment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient'),
        ),
        migrations.AddField(
            model_name='allergy_medication',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Allergy'),
        ),
        migrations.AddField(
            model_name='allergy_medication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Medication'),
        ),
        migrations.AddField(
            model_name='ailment_medication',
            name='ailment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Ailment'),
        ),
        migrations.AddField(
            model_name='ailment_medication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Medication'),
        ),
    ]
