# Generated by Django 2.2.7 on 2020-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_reminder_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailment',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
