# Generated by Django 2.2.7 on 2020-03-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
