# Generated by Django 2.2.7 on 2020-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200304_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='rem_date',
            field=models.DateField(),
        ),
    ]
