# Generated by Django 2.2.7 on 2020-04-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='family',
        ),
    ]
