# Generated by Django 2.2.7 on 2020-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_patient_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy_medication',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='allergy_medication',
            name='medication',
        ),
        migrations.DeleteModel(
            name='Ailment_Medication',
        ),
        migrations.DeleteModel(
            name='Allergy_Medication',
        ),
    ]
