# Generated by Django 2.2.7 on 2020-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_remove_visit_doctor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor_notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
