# Generated by Django 2.2.7 on 2019-12-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pin', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('DOB', models.DateTimeField()),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=400)),
                ('occupation', models.CharField(max_length=30)),
                ('marital_status', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('heart_rhythm', models.PositiveIntegerField()),
                ('oxygen_saturation', models.FloatField()),
                ('blood_pressurre', models.FloatField()),
                ('urinalysis_glucose', models.FloatField()),
                ('urinalysis_blood', models.FloatField()),
                ('urinalysis_protein', models.FloatField()),
                ('blood_count', models.FloatField()),
                ('fasting_glucose', models.FloatField()),
                ('chol_overall', models.FloatField()),
                ('chol_HDL', models.FloatField()),
                ('chol_LDL', models.FloatField()),
                ('uric_acid', models.FloatField()),
                ('triglyceride', models.FloatField()),
                ('smoke_per_day', models.PositiveIntegerField()),
                ('alcohol_per_week', models.PositiveIntegerField()),
                ('recreational_drugs', models.BooleanField()),
                ('exercise', models.BooleanField()),
                ('healthy_diet', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Doctor')),
                ('p_examined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Patient')),
            ],
        ),
    ]
