# Generated by Django 2.2.7 on 2019-12-14 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pin', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=400)),
                ('occupation', models.CharField(max_length=30)),
                ('marital_status', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(max_length=6)),
                ('chest_pain', models.CharField(max_length=50)),
                ('blood_systolic', models.FloatField()),
                ('blood_diastolic', models.FloatField()),
                ('chol_overall', models.FloatField()),
                ('smoke_per_day', models.PositiveIntegerField()),
                ('smoker_years', models.PositiveIntegerField()),
                ('fasting_glucose', models.FloatField()),
                ('hist_diabetes', models.BooleanField()),
                ('hist_heart_disease', models.BooleanField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('exerc_angina', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
