# Generated by Django 2.2.7 on 2019-12-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='user',
        ),
    ]
