# Generated by Django 2.2.7 on 2019-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='chest_pain',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='sex',
            field=models.PositiveIntegerField(),
        ),
    ]
