# Generated by Django 2.2.7 on 2020-02-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='acc_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Family'),
        ),
    ]
