# Generated by Django 2.2.7 on 2020-02-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200213_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_history',
            name='exam',
        ),
    ]
