# Generated by Django 2.2.7 on 2020-02-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_remove_examination_exerc_angina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='pulse_rate',
            new_name='heart_rate',
        ),
    ]
